name:                newsserver
version:             0.1.0.0
github:              "DenDragonB/newsserver"
license:             BSD3
author:              "DenDragonB"
maintainer:          "DenDragon@mail.ru"
copyright:           "2021 DenDragonB"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/newsserver#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- bytestring
- aeson
- time
- text
- htoml
- postgresql-simple
- resource-pool
- utf8-string
- wai
- warp
- http-types

library:
  source-dirs: src

executables:
  newsserver-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - newsserver

tests:
  newsserver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - newsserver
