INSERT INTO
MigrationHistory ( MajorVersion, MinorVersion, FileNumber, Comment,    DateApplied )
VALUES           ( '01',         '01',         '0001',     '0001',     NOW() );

CREATE TABLE Comments
    ( Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    , Comment TEXT ARRAY
    );