INSERT INTO
MigrationHistory ( MajorVersion, MinorVersion, FileNumber, Comment,    DateApplied )
VALUES           ( '01',         '01',         '0005',     '0005',     NOW() );

CREATE TABLE DraftsToTags 
    ( Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY 
    , DraftId INT NOT NULL
    , TagId INT NOT NULL
	, UNIQUE (DraftId,TagID)
    , FOREIGN KEY (DraftId) REFERENCES Drafts (Id) ON DELETE CASCADE ON UPDATE CASCADE
    , FOREIGN KEY (TagId) REFERENCES Tags (Id) ON DELETE CASCADE ON UPDATE CASCADE);