INSERT INTO
MigrationHistory ( MajorVersion, MinorVersion, FileNumber, Comment,    DateApplied )
VALUES           ( '01',         '01',         '0006',     '0006',     NOW() );

CREATE TABLE NewsToTags 
    ( Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY 
    , NewsId INT NOT NULL
    , TagId INT NOT NULL
	, UNIQUE (NewsId,TagID)
    , FOREIGN KEY (NewsId) REFERENCES News (Id) ON DELETE CASCADE ON UPDATE CASCADE
    , FOREIGN KEY (TagId) REFERENCES Tags (Id) ON DELETE CASCADE ON UPDATE CASCADE);

INSERT INTO draftstotags (draftid,tagid)
SELECT d.id,UNNEST(d.tags) FROM drafts d
ON CONFLICT DO NOTHING;

INSERT INTO newsToTags (newsId,tagid)
SELECT n.id,UNNEST(n.tags) FROM news n
ON CONFLICT DO NOTHING;

ALTER TABLE drafts DROP COLUMN tags;
ALTER TABLE news DROP COLUMN tags;